version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
      include: scope
    groups:
      npm-production:
        dependency-type: production
        update-types:
          - patch
          - minor
      npm-development:
        dependency-type: development
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "04:30"
      timezone: UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
